# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('assets', 'assets')],
    hiddenimports=['pandas', 'matplotlib', 'numpy', 'requests', 'PyQt5', 'PyQt5.QtSvg'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio', 'functorch',
        'transformers', 'tokenizers', 'huggingface_hub',
        'sklearn', 'scikit-learn',
        'cv2', 'opencv-python',
        'timm', 'bitsandbytes', 'accelerate', 'peft',
        'tensorflow', 'tensorboard', 'onnx', 'onnxruntime',
        'scipy',
        'sympy',
        'IPython', 'jupyter', 'notebook',
        'pytest',
        'boto3', 'botocore', 's3transfer',
        'sqlalchemy', 'redis',
        'fastapi', 'starlette', 'uvicorn', 'gunicorn',
        'networkx',
        'Cython',
        'lxml',
        'h5py',
        'pydantic',
        'anyio', 'aiohttp',
        'regex',
        'sentencepiece',
        'einops',
        'safetensors',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FOSSEE_Visualizer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/favicon.ico',
)
